server:
  port: 8084
  tomcat:
    max-http-form-post-size: 10MB

spring:
  application:
    name: zhonghe-server
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev

system:
  zhong-he-config:
    label: '123456'
    device-id: '00001011'
    device-des: 'Alan测试'
    device-address: '测试分校1'
    manager-code: '12345668'
    nas-ip: '192.168.166.153'
    middle-ware-ip: '192.168.166.153'
  tcp-host: zhonghe.tuoyang.vip
  tcp-port: 28085
